### ISSUE TITLE
Windows won't let me whitelist your app

### ISSUE THREAD

**Issue by Loftaris** [Nickswoboda/all-ears-unturned#5]
Windows Defender has decided all of a sudden, that your app is worse than COVID-19, and anytime I try to whitelist it or prevent it from being deleted, it refuses and deletes it anyways.

I've tried several ways to stop Windows Defender (short of turning it off... no-no!)

**Comment by mseetin** [comment]
It's not being blocked just for being an unverified app or something.  Windows Defender is specifically detecting a trojan, Wacatac.B!ml.  The publisher has some 'splainin to do.  Maybe he's unwittingly publishing corrupted files, but I would not use this program right now.

**Comment by Loftaris** [comment]
Agreed.  I've removed it entirely.  Funny though no other virus app
detected anything (I tried uploading it to a few sites)

**Comment by mseetin** [comment]
Looks like 1.1.4 doesn't have the same issues.

**Comment by Nickswoboda** [comment]
I tried downloading the most recent release and was having problems as well. Microsoft wouldn't even let the download succeed due to detecting a virus. I recompiled the program and updated the .zip for the v1.1.5 release and it seems to work now. So if you want, you may try downloading it again and see if that helped.

From my understanding it's due to false positives reported by the anti-virus software. These programs look for patterns and heuristics that indicate something might be malicious and marks them as such. Unfortunately I'm unaware of what pattern is causing the virus detection so I can't really fix the underlying issue yet.

Using [VirusTotal.com](virustotal.com) shows that both [v1.1.4](https://www.virustotal.com/gui/file/0b77488e4ae333cb89a347854e01853d4f7077c9fd1aa3b2caf70bc8b7b4fe82/detection) and [v1.1.5](https://www.virustotal.com/gui/file/c865d9f8b2fa8b8a6f1e0dcc8f7d57f42cfc7b75620ea967e4a3dc1bc78c671a/detection) can potentially have viruses although Microsoft only detects it for v1.1.5.

Temporary solutions would be either to use v.1.1.4, which is fully functional, just lacks some QoL. Or you may download the source code and compile the program on your own computer.

**Comment by Nickswoboda** [comment]
After the submitting the executable to Microsoft, they have removed the detection. If you update your antivirus virus and malware definitions, it should work fine. Please let me know if you still have any other issues.

**Comment by Zig216** [comment]
I have updated my windows antivirus but it is still detecting a trojan Wacatac.C!ml

**Comment by Nickswoboda** [comment]
> I have updated my windows antivirus but it is still detecting a trojan Wacatac.C!ml

Which antivirus are you using? Windows Defender, Microsoft Essentials, or a different one?

**Comment by Zig216** [comment]
> 
> 
> > I have updated my windows antivirus but it is still detecting a trojan Wacatac.C!ml
> 
> Which antivirus are you using? Windows Defender, Microsoft Essentials, or a different one?

Windows Defender

**Comment by Nickswoboda** [comment]
> > > I have updated my windows antivirus but it is still detecting a trojan Wacatac.C!ml
> > 
> > 
> > Which antivirus are you using? Windows Defender, Microsoft Essentials, or a different one?
> 
> Windows Defender

Try doing this.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Let me know if you still have issues after that.

**Comment by nickbrooking** [comment]
I tried the MpCmdRun steps and still get the issue. I have to manually allow it in Windows Defender. That works for a day or so, but at some point Windows removes it again anyway.

**Comment by Nickswoboda** [comment]
> I tried the MpCmdRun steps and still get the issue. I have to manually allow it in Windows Defender. That works for a day or so, but at some point Windows removes it again anyway.

I have once again submitted the program for analysis to Microsoft. It seems that it's getting flagged now for Wacatac.**D**C!ml instead of just Wacatac.C!ml. Hopefully it will be resolved soon.

If this remains an issue I will just remove v1.1.5 and revert the current release to v1.1.4 which doesn't seem to have any issues. v1.1.4 is completely functional and just lacks some QoL updates.
