### ISSUE TITLE
Missing a dialogue in Act 3

### ISSUE THREAD

**Issue by MeTeC-FR** [Nickswoboda/all-ears-unturned#6]
Hey there.

It's now my second time that I try to follow steps by steps this nicely done guide but each time I end up to 186/187 at the end of Act 3, is this something normal ? 

I don't think this is coming from the guide as it should be updated since 1 year but from the game.

**Comment by Nickswoboda** [comment]
As far as I'm aware, the dialogues have not changed since the beginning of 3.9. I tested the guide in the beginning of the Heist league up through act 10 and it worked fine for me. I'm sorry it hasn't worked for you, I know it sucks having to start back Act 1 just because you missed one dialogue option. That's what makes this achievement such a pain. But unfortunately without more information about anything specific that might be missing, there really isn't much I can do. I'm not sure if this is the problem, but if you happen to attempt it again, but I think the one of the trickier parts of Act 3 is remembering to remove quest items in your inventory before talking to Fairgraves or Dialla. Other than that, just make sure to immediately listen to all dialogues before you progress through new areas or quests.

Hopefully that helps, but if you keep having issues, or anyone else, please let me know.

**Comment by jabaabuu** [comment]
I just level new character to start end of act 3 and i too have 186/187.
I did everything just like this guide said.

**Comment by patcolyn** [comment]
I can confirm I am also experiencing the same issue. I have completed up to the The Aquaduct and I am missing a single dialog. I have made 100% sure to follow every step to a T on two characters, achieving the same outcome.

**Comment by Nickswoboda** [comment]
Alright. I'll run through it and see if I can find the issue. I'll probably also add a running total of xxx/505 at the end of each dialog grouping every time you go back to town instead of only at the end of each act. Hopefully that will help find future issues easier. I do not have an ETA on when I'll be able to get to it though.

**Comment by Ambient-Impact** [comment]
> Alright. I'll run through it and see if I can find the issue. I'll probably also add a running total of xxx/505 at the end of each dialog grouping every time you go back to town instead of only at the end of each act. Hopefully that will help find future issues easier. I do not have an ETA on when I'll be able to get to it though.

That would be really helpful. I get that you're doing this on your own time, and as a time constrained person myself (never enough time in a day to get all the stuff done that I want/need), I appreciate the work you've put into this.

I would also add that it would be great if the counter could specify exactly when we should have x/505, i.e. right after talking to an NPC after checking this or that line, as I found that confusing at the end of act 2 where it displayed the counter and it had checkboxes for dialogue on the same screen - my achievement counter in the game had one less than what was in your app until got that dialogue on the same page with the counter, so I'm wondering if I missed one or that was correct?

**Comment by Nickswoboda** [comment]
Since the new league was released I finally had time to run through the acts again. I can confirm that the number at the end of each Act is indeed accurate. But just because it's accurate, doesn't mean the guide can't be improved to make it easier to follow.
To that end, I just released [v1.2.0](https://github.com/Nickswoboda/all-ears-unturned/releases/tag/v1.2.0) which has some improvements.
A progress bar has been added to the top that tells you x/505 you should be at for any step in the guide. This should allow people to find issues earlier, before the end of each act. 
Notes for dialogs have been moved to the top of the step. This makes the "DO NOT HAVE X IN YOUR INVENTORY" notes the first thing you see during the step.
There were also some changes to the steps, but nothing that should affect the progression of the achievement.

Hopefully this changes will help if any of you decided to attempt the achievement again. If you still have problems please let me know.

**Comment by Ambient-Impact** [comment]
Awesome, thanks! Will check out sometime.
